### PR TITLE
Add color picker intensity to color picker

### PR DESCRIPTION
**Pull request by Legoman99573**
This would add intensity to the color picker. I would add to the core code to set a max value, but I am not that skilled at math to make it work and is open to edits to make it possible.

### CODE REVIEW

**Comment by Metamaniac** [comment]
?
image

**Comment by Legoman99573** [comment]
I'll take a look at it.

**Comment by Legoman99573** [comment]
Problems should be fixed. Let me know if its still occuring.

**Comment by Metamaniac** [comment]
Getting off break and found some time to fix the issues, implementation works/looks great!

**Pull request merged**
