### PR TITLE
New Physics, Other Upgrades, 2022 update

### PR DESCRIPTION
**Pull request by FairlySadPanda**
This covers the development branch as it is on the 11th of December. There's a diverging history on the older branch which I will orphan for the time being.

### CODE REVIEW

**Comment by metaphira** [comment]
Someone shared this with me so I just wanted to say that I would appreciate a mention in the credits if the final PR includes the physics I spent a good chunk of time bashing my head against the wall on (as evidenced by the comments I left). That being said, it's up to you and I'm certainly not planning on repeating history by threatening DMCA or whatever, the code was and continues to be ambiguously licensed.

**Comment by FairlySadPanda** [comment]
Yup, fundamentally the physics is a backport/minor cleanup of newer code written after the VRCBCE fork. We'll not be claiming it's novel and will be attributing work appropriately.

That said we need to get this PR over the line first

**Comment by FairlySadPanda** [comment]
@metaphira I've got this over the line into general testing before we ship 1.6.0 and I've taken a guess at adding a credit note for you in the readme. Let me know if you want to plug your codebase and I'm happy to promote it in our readme. (I don't know much about the situation regarding Pool Parlour, your code and involvement, I'm afraid, so if my exact understanding of your fork's history is wrong let me know and I can update it)

**Comment by metaphira** [comment]
Appreciate the quick turnaround! For full context, I maintained both the codebase and the world until around this time last year when I transferred ownership of both to @Toasterly. A little while after that, he asked for and I gave him permission to open source the codebase. He has since made additional changes, both open-source and closed-source. As such, I would welcome his opinion around specific phrasing (absent any, the current revision looks good to me) and defer to his opinion entirely on cross-promotion. As a small optimization, if Toaster would like to credit "Pool Parlor" in lieu of one or both of us by name, I'm fine with that.

While I'm here, I also wanted to apologize for #190, which is both unprofessional and disrespectful. I don't endorse or support that sort of behavior (nor, I would assume, does Toaster or the rest of the community) and I'm sorry that someone acted like that to you.

**Comment by Toasterly** [comment]
Would just like to say that it seems very disingenuous to have an alternative branch for this update, multiple merge and pull requests, and still not mention Metaphira or the Parlor throughout this anywhere in any readme or commit until after you were called out for this behavior. 

Alongside this you took the physics code without asking anybody at all for permission, "not knowing" the codebase or it's history is not an excuse for this. The Github was listed under having no license, which means all code contained within except for Harry-T's is strictly owned by the Parlor.

**You had no right to take without asking, and in my opinion you should not use the Parlor's physics code anywhere within your prefab due to how you've gone about this.**

**Comment by FairlySadPanda** [comment]
"The Github was listed under having no license" is incorrect. I've taken a look at the code repository in my archive (as it's been pulled), and I'm checking commit dd277b42c971a79e029eb21f631ac64dff7c567a, which was HEAD of master as of 15th Jan 2023.

BilliardsModule's license as of that time, when I grabbed the code and explored it, read:

"This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>"

**Comment by Toasterly** [comment]
Would like to apologize for the mistake on my part about licensing, I had forgotten that I changed the license out of concern from other content creators, also multiple people were telling me it was still unlicensed. Besides this though, my point was not to make any sort of threat to panic you with that statement, I would never attempt to take down this repo. 

Honestly up until now I have been rude to you so I am sorry, the Github table has been a thorn in my side for a long time and a massive headache. My patience with anything related to it is short admittedly.

**in my opinion** it was wrong to wait this long(3+ weeks of this being on git) to credit the proper person for the physics which you are backporting. Especially when there was a branch which contained this code and it's own readme, it should have been more than possible to credit them sooner.

After taking some time I understand that I was in the wrong here and would be glad if you used the phys. I'm just annoyed at the process you took when crediting the work used, but that is my problem. When your 1.6.0 release is pushed I will direct people to this table instead for their worlds.

Besides this I'd like to apologize again for being so hot headed in my responses, it's been a stressful time dealing with the table and I get questions constantly asked about it. I am honestly glad VRCBCE is taking the physics and maintaining it in their own table, this allows me to go back to working in private without an annoying prefab to deal with.

As for who to include in credits for the borrowed work, only include Metaphira. In the future I may contribute the updated physics that I worked on after they are fine tuned, but until then bye-bye.

**Comment by FairlySadPanda** [comment]
Hey, no worries. All the best with Pool Parlour, both the world and the table. It's always been cool.

I'll update our PR template to make sure that it flags that code must be sourced properly etc. This could have been avoided with responsible process and thanks for flagging this.

**Pull request merged**
